### ISSUE TITLE
trouble installing argosTrack

### ISSUE THREAD

**Issue by melindaconners** [calbertsen/argosTrack#5]
Hello,

I am trying to install argosTrack trying both: 
R> devtools::install_github("calbertsen/argosTrack") 
R> devtools::install_github("calbertsen/argosTrack",ref="mac")
 
but am encountering this error:
Error: HTTP error 404.
  Not Found
Did you spell the repo owner (`calbertsen`) and repo name (`argosTrack`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo._**

I have have devtools and TMB installed and am running R on Mac 10.13.6 High Sierra.
Have you encountered this before?

Any help would be much appreciated. Thank you for your work on this package - I'm looking forward to trying it out.

Melinda

**Comment by calbertsen** [comment]
I haven’t seen that error before, but the mac branch doesn’t exist any more. It was merged in to the master branch, so it makes sense to get the error for that branch.

Does it work if you run:

devtools::install_github("calbertsen/argosTrack/argosTrack", ref = "master")

**Comment by melindaconners** [comment]
That worked - Thanks much!
